#!/bin/sh
#-------------------------------------------------------------------------------------# 
# PURPOSE: run file for bio_block
#-------------------------------------------------------------------------------------# 
#-------------------------------------------------------------------------------------# 
# source the ciop functions (e.g. ciop-log)
source ${ciop_job_include}

export -p IXDIR=/application/bio_input_collecting/bin/
export -p IR=/application/parameters/AOI
export -p YR=/application/parameters/LULC
export -p DIR=/data/auxdata/ISD/ISD000/
export -p Y2=$(cat /application/parameters/year)
export -p INP2=/application/parameters/vito
export -p ex=/application/parameters/LULC
#-------------------------------------------------------------------------------------# 
# JOB 1 - ESA to LULC_crop
#-------------------------------------------------------------------------------------# 
function icx() { 
exec $IXDIR"resample_aoi_0010100.sh" $1 &
wait
exec $IXDIR"resample_aoi_0010300.sh"
}

#-------------------------------------------------------------------------------------# 
while IFS='' read -r line || [[ -n "$line" ]]; do
	if [[ "$line" == AOI1 ]] ; then	
		echo "$line"
		icx $YR 
	elif [[ "$line" == AOI2 ]] ; then
		echo "$line"
		icx $YR
	elif [[ "$line" == AOI3 ]] ; then
		echo "$line"
		icx $YR
	elif [[ "$line" == AOI4 ]] ; then
		echo "$line"
		icx $YR
	else
		echo "AOI out of range"
	fi 
done < "$IR"
#-------------------------------------------------------------------------------------# 
#-------------------------------------------------------------------------------------# 
#-------------------------------------------------------------------------------------# 
# JOB 2 - VITO to NIR/NDV/RED.tif
# Images (VITO), SNAP Toolbox crop PROBA-V and SPOT-VGT
#-------------------------------------------------------------------------------------# 
#-------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------------# 
function probav(){
while IFS='' read -r line || [[ -n "$line" ]]; do
	if [[ "$line" == AOI1 ]] ; then
		grep "X16Y03" $INP2 > $DIR/list.txt
		grep "X17Y03" $INP2 >> $DIR/list.txt
		grep "X18Y03" $INP2 >> $DIR/list.txt
		echo "${AOI=$(echo AOI1 )}"
		IMG001=$(grep $Y2 $2)
		Cx1=$(grep "Cx001" $2)
		igcx $Cx1 $IMG001 $AOI
		echo "AOI1"

	elif [[ "$line" == AOI2 ]] ; then
		grep "Y03" $INP2 > $DIR/list.txt
		grep "Y04" $INP2 >> $DIR/ist.txt
		grep "Y05" $INP2 >> $DIR/ist.txt
		echo "${AOI=$(echo AOI2 )}"
		IMG001=$(grep $Y2 $2)
		Cx1=$(grep "Cx001" $2)
		igcx $Cx1 $IMG001 $AOI
	        echo "AOI2"

	elif [[ "$line" == AOI3 ]] ; then
		grep "X20" $INP2 > $DIR/list.txt
		grep "X21" $INP2 >> $DIR/list.txt
		grep "X22" $INP2 >> $DIR/list.txt
		echo "${AOI=$(echo AOI3 )}"
		IMG001=$(grep $Y2 $2)
		Cx1=$(grep "Cx001" $2)
		igcx $Cx1 $IMG001 $AOI
		echo "AOI3"

	elif [[ "$line" == AOI4 ]] ; then
		grep "X20Y03" $INP2 > $DIR/list.txt
		grep "X21Y03" $INP2 >> $DIR/list.txt
		grep "X19Y03" $INP2 >> $DIR/list.txt
		echo "${AOI=$(echo AOI4 )}"
		IMG001=$(grep $Y2 $2)
		Cx1=$(grep "Cx001" $2)
		igcx $Cx1 $IMG001 $AOI
		echo "AOI4"
	else
		echo "PROBA-V out of range"
	fi 
done < "$IR"
}

function igcxs(){
exec $IXDIR"resample_aoi_0010700.sh" $1 $2 $3 &
wait
exec $IXDIR"resample_aoi_0010900.sh"
}

function spot_v(){
while IFS='' read -r line || [[ -n "$line" ]]; do
	
	if [[ "$line" == AOI1 ]] ; then
		echo "${AOI=$(echo AOI1 )}"
		IMG001=$(grep $Y2 $INP2)
		Cx1=$(grep "Cx001" $INP2)
		igcxs $Cx1 $IMG001 $AOI
		echo "AOI1"
	
	elif [[ "$line" == AOI2 ]] ; then
		echo "${AOI=$(echo AOI2 )}"
		IMG001=$(grep $Y2 $INP2)
		Cx1=$(grep "Cx001" $INP2)
		igcxs $Cx1 $IMG001 $AOI
	        echo "AOI2"

	elif [[ "$line" == AOI3 ]] ; then
		echo "${AOI=$(echo AOI3 )}"
		IMG001=$(grep $Y2 $INP2)
		Cx1=$(grep "Cx001" $INP2)
		igcxs $Cx1 $IMG001 $AOI
		echo "AOI3"

	elif [[ "$line" == AOI4 ]] ; then
		echo "${AOI=$(echo AOI4 )}"
		IMG001=$(grep $Y2 $INP2)
		Cx1=$(grep "Cx001" $INP2)
		igcxs $Cx1 $IMG001 $AOI
		echo "AOI4"
	else
		echo "AOI out of range"
	fi 
done < "$IR"
}

if ((Y2<2014)) ; then
    
    spot_v 
else
    probav
fi

#-------------------------------------------------------------------------------------# 
function igcx(){
exec $IXDIR"resample_aoi_0010701.sh" $1 $2 $3 &
wait
exec $IXDIR"resample_aoi_0010900.sh"
}

#-------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------------#
exit 0
