#!/bin/sh
#-------------------------------------------------------------------------------------# 
# PURPOSE: input data ECWMF
#-------------------------------------------------------------------------------------# 

# source the ciop functions (e.g. ciop-log)
source ${ciop_job_include}

export -p IDIR=/application/
echo $IDIR

#-------------------------------------------------------------------------------------# 
#-------------------------------------------------------------------------------------# 
export -p DIR=/data/auxdata/ISD/ISD000/
export -p CXDIR=$IDIR/cli_block_a/bin/
export -p IR=$IDIR/parameters/AOI
export -p YR=$IDIR/parameters/year
export -p Y2="$(cat $YR)"
#-------------------------------------------------------------------------------------# 
hcx(){
exec $CXDIR"ini.sh"
}
hcx

cd $DIR

if ((Y2<=2003)) ; then
    export -p Y1=$(($Y2-20))
    echo "20 years"
else
    export -p Y1=$(($Y2-25))
    echo "25 years"
fi

echo "Here:" $Y2

echo $Y1 $Y2 > $DIR/AOI.txt

#-------------------------------------------------------------------------------------# 
while IFS='' read -r line || [[ -n "$line" ]]; do
	if [[ "$line" == AOI1 ]] ; then

		for file in $(eval echo {$Y2..$Y1..5}); do
		h=$(expr $file - 5)
		echo $h $file			
		echo "$h $file 44.00 -9.75 36.00 3.50 0.75" > $DIR/AOI_$file.txt
		aoi=$(cat $DIR/AOI_$file.txt ); echo "$aoi" 
		years=$(awk '{print $1, $2}' $DIR/AOI_$file.txt)
		chmod 777 $CXDIR/climatic_dataset_000001.sh
		bash $CXDIR"climatic_dataset_000001.sh" $aoi
		
		done


	elif [[ "$line" == AOI2 ]] ; then

		for file in $(eval echo {$Y2..$Y1..5}); do
		h=$(expr $file - 5)
		echo $h $file			
		echo "$h $file 37.5 -19.0 12.0 25.5 0.75" > $DIR/AOI_$file.txt
		aoi=$(cat $DIR/AOI_$file.txt ); echo "$aoi" 
		years=$(awk '{print $1, $2}' $DIR/AOI_$file.txt)
		chmod 777 $CXDIR/climatic_dataset_000001.sh
		bash $CXDIR"climatic_dataset_000001.sh" $aoi
		
		done


	elif [[ "$line" == AOI3 ]] ; then

		for file in $(eval echo {$Y2..$Y1..5}); do
		h=$(expr $file - 5)
		echo $h $file			
		echo "$h $file -9.0 21.0 -31.5 41.0 0.75" > $DIR/AOI_$file.txt
		aoi=$(cat $DIR/AOI_$file.txt ); echo "$aoi" 
		years=$(awk '{print $1, $2}' $DIR/AOI_$file.txt)
		chmod 777 $CXDIR/climatic_dataset_000001.sh
		bash $CXDIR"climatic_dataset_000001.sh" $aoi
		
		done


	elif [[ "$line" == AOI4 ]] ; then
		
		for file in $(eval echo {$Y2..$Y1..5}); do
		h=$(expr $file - 5)
		echo $h $file			
		echo "$h $file 42.5 25.5 36.0 45.0 0.75" > $DIR/AOI_$file.txt
		aoi=$(cat $DIR/AOI_$file.txt ); echo "$aoi" 
		years=$(awk '{print $1, $2}' $DIR/AOI_$file.txt)
		chmod 777 $CXDIR/climatic_dataset_000001.sh
		bash $CXDIR"climatic_dataset_000001.sh" $aoi
		
		done	

	else
		echo "AOI out of range"
	fi 
done < "$IR"

#-------------------------------------------------------------------------------------#
fcx(){
years=$(awk '{print $1, $2}' $DIR/AOI.txt)

exec $CXDIR"climatic_dataset_001000.sh" $years &
wait
exec $CXDIR"climatic_dataset_001001.sh" $years &
wait
exec $CXDIR"climatic_dataset_001003.sh" &
#wait
#exec $CXDIR"climatic_dataset_001002.sh" &
wait
exec $CXDIR"climatic_dataset_001005.sh" &
wait
exec $CXDIR"climatic_dataset_002000.sh" $years &
wait
exec $CXDIR"climatic_dataset_002001.sh" $years &
wait
exec $CXDIR"climatic_dataset_002003.sh" &
#wait
#exec $CXDIR"climatic_dataset_002002.sh" &
wait
exec $CXDIR"climatic_dataset_002005.sh"    
}


#-------------------------------------------------------------------------------------# 
while IFS='' read -r line || [[ -n "$line" ]]; do
	if [[ "$line" == AOI1 ]] ; then
	        echo "${AOI1=$(echo $Y1 $Y2 44.00 -9.75 36.00 3.50 0.75)}" 
		fcx
	elif [[ "$line" == AOI2 ]] ; then
		echo "${AOI2=$(echo $Y1 $Y2 37.5 -19.0 12.0 25.5 0.75)}" 
		fcx
	elif [[ "$line" == AOI3 ]] ; then
		echo "${AOI3=$(echo $Y1 $Y2 -9.0 21.0 -31.5 41.0 0.75)}" 
		fcx
	elif [[ "$line" == AOI4 ]] ; then
		echo "${AOI4=$(echo $Y1 $Y2 42.5 25.5 36.0 45.0 0.75)}" 
		fcx
	else
		echo "AOI out of range"
	fi 
done < "$IR"

#-------------------------------------------------------------------------------------# 
echo "DONE"
echo 0




