#!/bin/sh
#-------------------------------------------------------------------------------------# 
# PURPOSE: run file for ISD
#-------------------------------------------------------------------------------------# 
start=`date +%s`
source {ciop_job_include}
#-------------------------------------------------------------------------------------# 


/application/cli_block_a/run
/application/bio_input_collecting/run
/application/bio_block_p1/run
/application/bio_block_a/run
/application/bio_block_p2/run
/application/processing_block_p/run
/application/processing_block_a/run
