#!/bin/sh
#-------------------------------------------------------------------------------------# 
# PURPOSE: run file for ISD
#-------------------------------------------------------------------------------------# 
start=`date +%s`
source {ciop_job_include}

export -p IXDIR=/application/
#-------------------------------------------------------------------------------------# 
function igcx(){

exec $IXDIR"cli_block_a/run" &
wait
exec $IXDIR"bio_input_collecting/run" & 
wait
exec $IXDIR"bio_block_p1/run" &
wait 
exec $IXDIR"bio_block_a/run" &
wait
exec $IXDIR"bio_block_p2/run" & 
wait
exec $IXDIR"processing_block_p/run" &
wait 
exec $IXDIR"processing_block_a/run" & 
}
igcx


#-------------------------------------------------------------------------------------# 
echo "DONE"
echo 0


