#!/bin/sh
#-------------------------------------------------------------------------------------# 
# PURPOSE: run file for Ix
#-------------------------------------------------------------------------------------# 
#-------------------------------------------------------------------------------------# 
# source the ciop functions (e.g. ciop-log)
source ${ciop_job_include}

export -p IXDIR=/application/bio_block_p1/bin/
export -p IR=/application/parameters/AOI
#-------------------------------------------------------------------------------------# 
# JOB 1
#-------------------------------------------------------------------------------------# 
#-------------------------------------------------------------------------------------# 
function icx()
{
exec $IXDIR"resample_aoi_00105.sh"
}
icx
#-------------------------------------------------------------------------------------#
# JOB 2
#-------------------------------------------------------------------------------------# 
#-------------------------------------------------------------------------------------# 
function igcx(){
exec $IXDIR"vgt_to_geoms_00100.sh" $1 $2
}
#-------------------------------------------------------------------------------------# 
while IFS='' read -r line || [[ -n "$line" ]]; do
	if [[ "$line" == AOI1 ]] ; then	
		NV=$(grep "NDV001" $2)
		LC=$(grep "LANDC001" $2)
		igcx $NV $LC
	
	elif [[ "$line" == AOI2 ]] ; then		
		NV=$(grep "NDV001" $2)
		LC=$(grep "LANDC001" $2)
		igcx $NV $LC

	elif [[ "$line" == AOI3 ]] ; then		
		NV=$(grep "NDV001" $2)
		LC=$(grep "LANDC001" $2)
		igcx $NV $LC

	elif [[ "$line" == AOI4 ]] ; then
		NV=$(grep "NDV001" $2)
		LC=$(grep "LANDC001" $2)
		igcx $NV $LC
	else
		echo "AOI out of range"
	fi 
done < "$IR"
#-------------------------------------------------------------------------------------# 
function igcs(){
exec $IXDIR"vgt_to_geoms_00200.sh" $1 $2 $3
}
#-------------------------------------------------------------------------------------# 
while IFS='' read -r line || [[ -n "$line" ]]; do
	if [[ "$line" == AOI1 ]] ; then	

		NI=$(grep "NIR001" $2)
		RE=$(grep "RED001" $2)
		LC=$(grep "LANDC001" $2)

		igcs $NI $LC $RE 
	
	elif [[ "$line" == AOI2 ]] ; then
		
		NI=$(grep "NIR001" $2)
		RE=$(grep "RED001" $2)
		LC=$(grep "LANDC001" $2)
		igcs $NI $LC $RE 

	elif [[ "$line" == AOI3 ]] ; then
		
		NI=$(grep "NIR001" $2)
		RE=$(grep "RED001" $2)
		LC=$(grep "LANDC001" $2)
		igcs $NI $LC $RE 

	elif [[ "$line" == AOI4 ]] ; then
		
		NI=$(grep "NIR001" $2)
		RE=$(grep "RED001" $2)
		LC=$(grep "LANDC001" $2)
		igcs $NI $LC $RE 
	else
		echo "AOI out of range"
	fi 
done < "$IR"

#-------------------------------------------------------------------------------------# 
#-------------------------------------------------------------------------------------# 
#-------------------------------------------------------------------------------------# 
function igcr(){
exec $IXDIR"vgt_to_geoms_00400.sh" $1 $2
}
#-------------------------------------------------------------------------------------# 
while IFS='' read -r line || [[ -n "$line" ]]; do
	if [[ "$line" == AOI1 ]] ; then	
		RE=$(grep "NDV02" $2)
		LC=$(grep "LANDC001" $2)
		igcr $RE $LC 
	
	elif [[ "$line" == AOI2 ]] ; then		
		RE=$(grep "NDV02" $2)
		LC=$(grep "LANDC001" $2)
		igcr $RE $LC 

	elif [[ "$line" == AOI3 ]] ; then
		RE=$(grep "NDV02" $2)
		LC=$(grep "LANDC001" $2)
		igcr $RE $LC 

	elif [[ "$line" == AOI4 ]] ; then		
		RE=$(grep "NDV02" $2)
		LC=$(grep "LANDC001" $2)
		igcr $RE $LC 
	else
		echo "AOI out of range"
	fi 
done < "$IR"
#-------------------------------------------------------------------------------------# 
echo "AGGREGATION.................1"
echo 0



