#!/bin/sh
#-------------------------------------------------------------------------------------# 
# PURPOSE: run file for Ix
#-------------------------------------------------------------------------------------# 
#-------------------------------------------------------------------------------------# 
# source the ciop functions (e.g. ciop-log)
source ${ciop_job_include}
#-------------------------------------------------------------------------------------# 
export DIR=/data/auxdata/ISD/ISD000/
if [ ! -d "$DIR" ]; then
    mkdir $DIR
fi

export -p IR=/application/parameters/AOI
export -p IXDIR=/application/bio_block_a/bin/
#-------------------------------------------------------------------------------------# 
function igcx(){
exec $IXDIR"vgt_to_geoms_00101.sh" & 
wait
exec $IXDIR"vgt_to_geoms_00103.sh" &  
wait
exec $IXDIR"vgt_to_geoms_00201.sh" & 
wait
exec $IXDIR"vgt_to_geoms_00203.sh" & 
wait
exec $IXDIR"vgt_to_geoms_00501.sh" &
wait
exec $IXDIR"vgt_to_geoms_00401.sh" 
}
#-------------------------------------------------------------------------------------# 
while IFS='' read -r line || [[ -n "$line" ]]; do
	if [[ "$line" == AOI1 ]] ; then	
		NV=$(grep "NDV001" $2)
		LC=$(grep "LANDC001" $2)
		igcx $NV $LC
	
	elif [[ "$line" == AOI2 ]] ; then		
		NV=$(grep "NDV001" $2)
		LC=$(grep "LANDC001" $2)
		igcx $NV $LC

	elif [[ "$line" == AOI3 ]] ; then		
		NV=$(grep "NDV001" $2)
		LC=$(grep "LANDC001" $2)
		igcx $NV $LC

	elif [[ "$line" == AOI4 ]] ; then
		NV=$(grep "NDV001" $2)
		LC=$(grep "LANDC001" $2)
		igcx $NV $LC
	else
		echo "AOI out of range"
	fi 
done < "$IR"
#-------------------------------------------------------------------------------------# 
echo "Done"
echo 0





