#!/bin/sh
#-------------------------------------------------------------------------------------# 
# PURPOSE: run file for Ix
#-------------------------------------------------------------------------------------# 
#-------------------------------------------------------------------------------------# 
# source the ciop functions (e.g. ciop-log)
# source ${ciop_job_include}
#-------------------------------------------------------------------------------------# 
export -p DIR=/data/auxdata/ISD/ISD000/
export -p IR=/application/parameters/AOI
export -p IXDIR=/application/bio_block_a/bin/
#-------------------------------------------------------------------------------------# 
function igcx(){
exec $IXDIR"vgt_to_geoms_00101.sh" & 
wait
exec $IXDIR"vgt_to_geoms_00103.sh" &  
wait
exec $IXDIR"vgt_to_geoms_00201.sh" & 
wait
exec $IXDIR"vgt_to_geoms_00203.sh" & 
wait
exec $IXDIR"vgt_to_geoms_00501.sh" &
wait
exec $IXDIR"vgt_to_geoms_00401.sh" 
}
#-------------------------------------------------------------------------------------# 
igcx
#-------------------------------------------------------------------------------------# 
exit 0





